### PR TITLE
Updates from multiple forks

### PR DESCRIPTION
**Pull request by grempe**
This PR includes updates from @KentHawkings and @grempe.

I needed to break and delete my fork from @KentHawkings and re-establish a new one to make this upstream PR.

I'll need to make a new release and update the tap as well now. You may pull in these commits, but the tap will point to releases on the @truestamp fork.  You are free to make your own tap of course.

### CODE REVIEW

**Comment by grempe** [comment]
A new release has been cut on the replacement fork.

https://github.com/truestamp/iterm-workspace/releases

The tap has been updated to point to this new release tarball.

https://github.com/truestamp/homebrew-tap/blob/main/Formula/iterm-workspace.rb

If you had installed from the tap since yesterday you'll probably want to `brew uninstall iterm-workspace` and `brew untap truestamp/tap` and then re-install both.

**Comment by grempe** [comment]
For posterity, the new tap formula (which I had to create from scratch as the old tap repo and its account owner @knrz are totally gone from GitHub):

```ruby
class ItermWorkspace < Formula
  desc "Configurable iTerm2 scripting for launching project workspace programs"
  homepage "https://github.com/truestamp/iterm-workspace"
  url "https://github.com/truestamp/iterm-workspace/archive/refs/tags/v2.0.0.tar.gz"
  sha256 "de198542a60219bcb848a69df40cfdbe2c170a0c1016ea8800e9a1d3f3f6efa8"
  license "MIT"

  def install
    bin.install "iterm-workspace"
    bin.install "bootstrap-iterm-workspace"
  end

  test do
    system "#{bin}/iterm-workspace"
  end
end
```

**Comment by CyrusNuevoDia** [comment]
Haha I'm @knrz !

**Comment by grempe** [comment]
> Haha I'm @knrz !

Huh? So you deleted your GitHub account, taking the previous tap and everything with it? Which then caused me to need to recreate the tap? Which you then asked for a PR to be pulled into your new account name?

Can I ask why you would do any of this?

**Comment by grempe** [comment]
Yeah, I see your old tap now in your list of repos.

https://github.com/DaoDeCyrus/homebrew-iterm-workspace

**Comment by CyrusNuevoDia** [comment]
@grempe I renamed my account for my new online pseudonym

Re: A PR, I figured since you'd gotten it working it would be great to just do a PR without having to recontextualize myself with all this.

**Pull request merged**
